version: '3.8'

services:
  movie-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${API_URL:-http://localhost:8000/api/v1}
    ports:
      - "3000:3000"
    environment:
      - API_URL=${API_URL:-http://localhost:8000/api/v1}
    container_name: movies
    restart: unless-stopped